from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from datetime import datetime
import os
import re


def clean_filename(text):
    """
    Removes invalid filename characters.
    """
    return re.sub(r'[\\/*?:"<>|]', "", text)


def create_lesson_doc(
    full_name,
    institution,
    summary,
    takeaway,
    original_filename
):

    document = Document()

    # -------------------------
    # TITLE
    # -------------------------

    title = document.add_heading("LEARNVOX", level=1)
    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    subtitle = document.add_heading("AI STUDY NOTES", level=2)
    subtitle.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    document.add_paragraph()

    # -------------------------
    # STUDENT DETAILS
    # -------------------------

    document.add_heading("Prepared For", level=3)
    document.add_paragraph(full_name)

    document.add_heading("Institution", level=3)
    document.add_paragraph(institution)

    document.add_heading("Study Material", level=3)
    document.add_paragraph(original_filename)

    document.add_heading("Generated", level=3)
    document.add_paragraph(
        datetime.now().strftime("%d %B %Y")
    )

    document.add_page_break()

    # -------------------------
    # AI TUTOR
    # -------------------------

    lesson_heading = document.add_heading(
        "AI TUTOR",
        level=1
    )

    lesson_heading.runs[0].font.size = Pt(18)

    document.add_paragraph(summary)

    # -------------------------
    # FOOTER
    # -------------------------

    document.add_page_break()

    footer = document.add_paragraph()

    footer.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    footer.add_run(
        "Generated by LearnVox AI\n"
    ).bold = True

    footer.add_run(
        "Your Personal AI Tutor for Every Study Material\n\n"
    )

    footer.add_run(
        "Built by Intechrity Consulting"
    )

    # -------------------------
    # SAVE FILE
    # -------------------------

    os.makedirs(
        "static/downloads",
        exist_ok=True
    )

    base_filename = clean_filename(
    os.path.splitext(original_filename)[0]
)

    filename = (
    f"{clean_filename(full_name)}_"
    f"{base_filename}_"
    f"AI_Study_Notes.docx"
)

    output_path = os.path.join(
        "static/downloads",
        filename
    )

    document.save(output_path)

    return "/static/downloads/" + filename

